service: nestjs-serverless-app

plugins:
  - serverless-offline
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs20.x
  profile: taurn
  region: ap-south-1
  deploymentBucket:
    name: bucketwithnestjscode
custom:
  prune:
    automatic: true
    number: 1
functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
          cors: 
            origins: '*'
      - http:
          method: ANY
          path: '{proxy+}'
          cors: 
            origins: '*'
